apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: release
  name: release
spec:
  replicas: 1
  selector:
    matchLabels:
      app: release
  strategy: {}
  template:
    metadata:
      labels:
        app: release
    spec:
      containers:
        - image: dhf0820/release_server:200618.6
          name: document-server-6jfzp
          resources: {}
          env:
            - name: DATABASE
              value: "test_release_service"
            - name: RELEASE_ADDRESS
              value: "0.0.0.0"
            - name: RELEASE_PORT
              value: "9910"
            - name: DBENV
              value: "mongodb"
            - name: CERTS
              value: "/etc/ssl/vscerts/linux_ssl"
            - name: ATLAS
              value: "mongodb+srv://dhf:Sacj0nhat1@cluster0-rcwui.mongodb.net/documents?retryWrites=true&w=majority"
            - name: MONGODB
              value: "mongodb://dhf:Sacj0nhat1@docker1.vertisoft.com:27017/?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256"
status: {}
