apiVersion: v1
kind: Service
metadata:
  name: release
  namespace: roi
  labels:
    app: release
spec:
  type: LoadBalancer
  selector:
    app: release
  ports:
    - name: grpc
      port: 9901
      targetPort: 9901
